### ISSUE TITLE
EC2 instance died after retrieving ironoc-pytest issues and POST request where static resource from REACT app was not resolved

### ISSUE THREAD

**Issue by conorheffron** [conorheffron/ironoc#142]
This is possibly a memory issue where a larger instance is needed to run the app over time.
See logs before 504 gateway errors

```shell
(UTC+1:00) | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.30.jar!/:?] | f03137f5b09a4f179981e5cc12711e91 | ironoc
-- | -- | -- | --
14 October 2024 at 12:19 (UTC+1:00) | at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] | f03137f5b09a4f179981e5cc12711e91 | ironoc
14 October 2024 at 12:19 (UTC+1:00) | 2024-10-14T11:19:13.345Z WARN 8 --- [nio-8080-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported] | f03137f5b09a4f179981e5cc12711e91 | ironoc
14 October 2024 at 12:11 (UTC+1:00) | 2024-10-14T11:11:37.096Z WARN 8 --- [nio-8080-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported] | f03137f5b09a4f179981e5cc12711e91 | ironoc
14 October 2024 at 11:43 (UTC+1:00) | 2024-10-14T10:43:59.888Z WARN 8 --- [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported] | f03137f5b09a4f179981e5cc12711e91 | ironoc
14 October 2024 at 11:15 (UTC+1:00) | 2024-10-14T10:15:54.142Z INFO 8 --- [io-8080-exec-10] n.i.p.l.AbstractLogger : The repository issues for user=conorheffron and repo=ironoc-pytest are: [] | f03137f5b09a4f179981e5cc12711e91 | ironoc
14 October 2024 at 11:15 (UTC+1:00) | 2024-10-14T10:15:53.870Z INFO 8 --- [io-8080-exec-10] n.i.p.l.AbstractLogger : Github list issues by username=conorheffron and repo=ironoc-pytest for request, host=ironoc.net, uri=/get-repo-issue/conorheffron/ironoc-pytest/, user-agent=Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.70 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) | f03137f5b09a4f179981e5cc12711e91 | ironoc
14 October 2024 at 11:15 (UTC+1:00) | 2024-10-14T10:15:53.870Z INFO 8 --- [io-8080-exec-10] n.i.p.l.AbstractLogger : Triggering GET request: url=https://api.github.com/repos/conorheffron/ironoc-pytest/issues?per_page=100&page=1 | f03137f5b09a4f179981e5cc12711e91 | ironoc

(UTC+1:00)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.30.jar!/:?]
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
14 October 2024 at 12:19 (UTC+1:00)
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
14 October 2024 at 12:19 (UTC+1:00)
2024-10-14T11:19:13.345Z WARN 8 --- [nio-8080-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported]
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
14 October 2024 at 12:11 (UTC+1:00)
2024-10-14T11:11:37.096Z WARN 8 --- [nio-8080-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported]
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
14 October 2024 at 11:43 (UTC+1:00)
2024-10-14T10:43:59.888Z WARN 8 --- [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported]
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
14 October 2024 at 11:15 (UTC+1:00)
2024-10-14T10:15:54.142Z INFO 8 --- [io-8080-exec-10] n.i.p.l.AbstractLogger : The repository issues for user=conorheffron and repo=ironoc-pytest are: []
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
14 October 2024 at 11:15 (UTC+1:00)
2024-10-14T10:15:53.870Z INFO 8 --- [io-8080-exec-10] n.i.p.l.AbstractLogger : Github list issues by username=conorheffron and repo=ironoc-pytest for request, host=ironoc.net, uri=/get-repo-issue/conorheffron/ironoc-pytest/, user-agent=Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.70 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
14 October 2024 at 11:15 (UTC+1:00)
2024-10-14T10:15:53.870Z INFO 8 --- [io-8080-exec-10] n.i.p.l.AbstractLogger : Triggering GET request: url=https://api.github.com/repos/conorheffron/ironoc-pytest/issues?per_page=100&page=1
[f03137f5b09a4f179981e5cc12711e91](https://eu-north-1.console.aws.amazon.com/ecs/v2/clusters/IronocPortfolioCluster/services/IronocService/tasks/f03137f5b09a4f179981e5cc12711e91?region=eu-north-1)
ironoc
```

**Comment by conorheffron** [comment]
A larger instance & end-point config was needed here. closing issue but will keep this issue in mind if appears again.
